#!/bin/bash
#OSINT via a name
#By: Jessica Ackerman @ScriptnKitten
#Last Update: 10/6/19
#format: osintName <firstName> <lastName>
#note: middle name intentionally excluded
#note: location intentionally excluded

first=$1
last=$2

#411
s1="https://www.411.com/name/"$first"-"$last"?q="$first"+"$last

#AdvancedBackgroundCheck
s2="https://www.advancedbackgroundchecks.com/names/"$first"-"$last

#FamilyTreeNow
s3="https://www.familytreenow.com/search/genealogy/results?first="$first"&last="$last

#FastPeopleSearch
s4="https://www.fastpeoplesearch.com/name/"$first"-"$last

#Intelius
s5="https://www.intelius.com/people-search/"$first"-"$last"?fullname="$first"%20"$last

#JohnDoe
s6="https://johndoe.com/people/"$first"-"$last

#PeekYou
s7="https://peekyou.com/"$first"_"$last

#PeopleFinder
s8="https://www.peoplefinder.com/people-search/"$first"-"$last"/"

#PeopleFinders
s9="https://www.peoplefinders.com/people/"$first"-"$last

#Radaris
s10="https://radaris.com/p/"$first"/"$last"/"

#Spokeo
s11="https://www.spokeo.com/"$first"-"$last"?loaded=1"

#That'sThem
s12="https://thatsthem.com/name/"$first"-"$last

#TruePeopleSearch
s13="https://www.truepeoplesearch.com/results?name="$first"%20"$last

#TruthFinder
s14="https://www.truthfinder.com/results/?firstName="$first"&lastName="$last"&city=&state=ALL"

#WebMii
s15="https://webmii.com/people?n=%22"$first"%20"$last"%22"

#Whitepages
s16="https://www.whitepages.com/name/"$first"-"$last"?q="$first"+"$last

#yasni
s17="http://www.yasni.com/"$first"+"$last"/check+people?sh"

#ZabaSearch
s18="https://www.zabasearch.com/people/"$first"+"$last"/"

#_____________________Sites in Progress_________________________#

#findPeopleSearch
s19="https://www.findpeoplesearch.com/"
#results are good, but input is troublesome included for manual input

#Dorking Failed Initial Attempts - will add later

#Facebook
g1=$first%20$last%20site:Facebook.com

#LinkedIn
g2=$first%20$last%20site:LinkedIn.com

#Twitter
g3=$first%20$last%20site:Twitter.com

#Instagram
g4=$first%20$last%20site:Instagram.com

#_______________________________________________________________#
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
do
	tempString='s'$i
	fString+=$" -new-tab -url "
	fString+=${!tempString}
done

for i in 1 2 3 4
do
	#DuckDuckGo dork
	tempString='g'$i
	fString+=$" -new-tab -url https://duckduckgo.com/?q="
	fString+=${!tempString}
	
	#Google dork
	tempString='g'$i
	fString+=$" -new-tab -url https://google.com/search?q="
	fString+=${!tempString}
done

firefox -private $fString 2>&1>/dev/null
