#!/bin/bash
#OSINT via phone number
#By: Jessica Ackerman @ScriptnKitten
#Last Update: 10/3/19
#format: osintNumber <phoneNumber>
#note: phone number presented as just numbers and no additional characters
#note: script should handle any numbers lengths 10-13, but sites may not support searching in areas outside the US

phone=$1

#split number for sites that require additional formatting
l=$(echo -n $phone | wc -c)
if [ "$l" = "10" ]; then
	b=$(echo -n $phone | cut -b 1-3)
	c=$(echo -n $phone | cut -b 4-6)
	d=$(echo -n $phone | cut -b 7-10)
else if [ "$l" = "11" ]; then
	a=$(echo -n $phone | cut -b 1)
	b=$(echo -n $phone | cut -b 2-4)
	c=$(echo -n $phone | cut -b 5-7)
	d=$(echo -n $phone | cut -b 8-11)	
else if [ "$l" = "12" ]; then
	a=$(echo -n $phone | cut -b 1-2)
	b=$(echo -n $phone | cut -b 3-5)
	c=$(echo -n $phone | cut -b 6-8)
	d=$(echo -n $phone | cut -b 9-12)
else if [ "$l" = "13" ]; then
	a=$(echo -n $phone | cut -b 1-3)
	b=$(echo -n $phone | cut -b 4-6)
	c=$(echo -n $phone | cut -b 7-9)
	d=$(echo -n $phone | cut -b 10-13)
fi; fi; fi; fi

#411
s1="https://www.411.com/phone/"$phone

#Facebook

#infotracer
s2="https://infotracer.com/phone-lookup/results/?phone="$phone

#PeekYou
s3="https://www.peekyou.com/phone/"$phone

#That's Them
s4="https://thatsthem.com/phone/"$b"-"$c"-"$d

#TruePeopleSearch
s5="https://www.truepeoplesearch.com/results?phoneno="$phone

#USPhonebook
s6="https://www.usphonebook.com/"$b"-"$c"-"$d

#Whitepages
s7="https://www.whitepages.com/phone/"$phone

#_______________________________________________________________#
for i in 1 2 3 4 5 6 7
do
        tempString='s'$i
        fString+=$" -new-tab -url "
        fString+=${!tempString}
done

firefox -private $fString
