#!/bin/bash
#OSINT via Email
#By: Jessica Ackerman @ScriptnKitten
#format: osintEmail <email>

email=$1

#split email
sEmail=(${email//@/ })

#_______________________________________________________________#
#411
s1="https://www.411.com/email/"

#AdvancedBackgroundchecks
s2="https://www.advancedbackgroundchecks.com/emails/"

#Spokeo
s3="https://www.spokeo.com/email-search/"

#That'sThem
s4="https://thatsthem.com/email/"$email

#_______________________________________________________________#
for i in 1 2 3 4
do
        tempString='s'$i
        fString+=$" -new-tab -url "
        fString+=${!tempString}
done

firefox -private $fString 2>&1>/dev/null
