#!/bin/bash
#OSINT via phone number
#By: Jessica Ackerman @ScriptnKitten
#format: osintNumber <phoneNumber>
#note: phone number presented as just numbers and no additional characters
#note: script should handle any numbers lengths 10-13, but sites may not search in areas outside the US* 

phone=$1

#split number for sites that require additional formatting
l=$(echo -n $phone | wc -c)
if [ "$l" = "10" ]; then
	a="1"
	b=$(echo -n $phone | cut -b 1-3)
	c=$(echo -n $phone | cut -b 4-6)
	d=$(echo -n $phone | cut -b 7-10)
else if [ "$l" = "11" ]; then
	a=$(echo -n $phone | cut -b 1)
	b=$(echo -n $phone | cut -b 2-4)
	c=$(echo -n $phone | cut -b 5-7)
	d=$(echo -n $phone | cut -b 8-11)	
else if [ "$l" = "12" ]; then
	a=$(echo -n $phone | cut -b 1-2)
	b=$(echo -n $phone | cut -b 3-5)
	c=$(echo -n $phone | cut -b 6-8)
	d=$(echo -n $phone | cut -b 9-12)
else if [ "$l" = "13" ]; then
	a=$(echo -n $phone | cut -b 1-3)
	b=$(echo -n $phone | cut -b 4-6)
	c=$(echo -n $phone | cut -b 7-9)
	d=$(echo -n $phone | cut -b 10-13)
fi; fi; fi; fi

#_______________________________________________________________#
#411
s1="https://www.411.com/phone/"$phone

#AdvancedBackgroundChecks
s2="https://www.advancedbackgroundchecks.com/"$b"-"$c"-"$d

#Facebook
s3="https://www.facebook.com/search/top/?q="$phone"&epa=SEARCH_BOX"

#FastPeopleSearch
s4="https://www.fastpeoplesearch.com/"$b"-"$c"-"$d

#infotracer
s5="https://infotracer.com/phone-lookup/results/?phone="$phone

#intelius
s6="https://www.intelius.com/reverse-phone-lookup/"$phone

#JohnDoe.com
s7="https://johndoe.com/phones/"$phone

#PeekYou
s8="https://www.peekyou.com/phone/"$phone

#PeopleFinder
s9="https://www.peoplefinder.com/reverse-phone-search/"$phone

#Spokeo
s10="https://www.spokeo.com/"$phone

#Sync.Me
s11="https://sync.me/search/?number="$a$b$c$d

#That's Them
s12="https://thatsthem.com/phone/"$b"-"$c"-"$d

#TruePeopleSearch
s13="https://www.truepeoplesearch.com/results?phoneno="$phone

#USPhonebook
s14="https://www.usphonebook.com/"$b"-"$c"-"$d

#Whitepages
s15="https://www.whitepages.com/phone/"$phone

#WhoCallsMe
s16="https://whocallsme.com/Phone-Number.aspx/"$phone

#ZabaSearch
s17="https://zabasearch.com/phone/"$phone

#_______________________________________________________________#
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
do
        tempString='s'$i
        fString+=$" -new-tab -url "
        fString+=${!tempString}
done

firefox -private $fString 2>&1>/dev/null
