#!/bin/bash
#OSINT via Instagram
#By: Jessica Ackerman @ScriptnKitten
#Last Update: 10/2/19
#format: osintInsta <username>

user=$1

#site
s1="url"

#_______________________________________________________________#
#Sites in Progress:

#_______________________________________________________________#
for i in 1
do
        tempString='s'$i
        fString+=$" -new-tab -url "
        fString+=${!tempString}
done

firefox -private $fString

