#!/bin/bash
#OSINT via Template
#By: Jessica Ackerman @ScriptnKitten
#Last Update: 10/1/19
#format: osintTemplate.sh <stuff>

x=$1
y=$2

#site
s1="url"

#_______________________________________________________________#
#Sites in Progress:

#_______________________________________________________________#
for i in 1
do
        tempString='s'$i
        fString+=$" -new-tab -url "
        fString+=${!tempString}
done

firefox $fString

